exports.Init = function(config) {}
exports.LogUser = function(deathbot, user) {}
exports.LogPlay = function(deathbot, song) {}
exports.GetTopDj = function(callback) {}
exports.GetTopDjs = function(amt, callback) {}
exports.GetTopPlay = function(callback) {}
exports.GetTopPlays = function(amt, callback) {}
exports.GetMyTopPlay = function(userId, callback) {}
exports.GetWorstSong = function(callback) {}
exports.GetWorstSongs = function(amt, callback) {}
exports.GetMyWorstSong = function(userId, callback) {}
exports.GetTopGrab = function(callback) {}
exports.GetTopGrabs = function(amt, callback) {}
exports.GetMyTopGrabbed = function(userId, callback) {}
exports.MostPlayedArtist = function(callback) {}
exports.GetMostPlayedArtists = function(amt, callback) {}
exports.MyMostPlayedArtist = function(userId, callback) {}
exports.MostPlayedSong = function(callback) {}
exports.MostPlayedSongs = function(amt, callback) {}
exports.MyMostPlayedSong = function(userId, callback) {}
exports.GetRoomStats = function(callback) {}